# Generated by Django 2.1.5 on 2019-03-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('blog', '0007_photoarchiveindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoarchiveindexpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='PhotoArchiveIndexPage',
        ),
    ]
