# Generated by Django 2.1.5 on 2019-04-29 17:02

from django.db import migrations, models
import django.db.models.deletion
import home.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalPage',
            fields=[
                ('homepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.HomePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.homepage',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('feature', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.core.blocks.CharBlock(help_text="An optional title to appear in the box. Leave blank if you don't want it.", required=False)), ('text', wagtail.core.blocks.RichTextBlock()), ('page', wagtail.core.blocks.PageChooserBlock(required=False))])), ('highlights', wagtail.core.blocks.StructBlock([('items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('page', wagtail.core.blocks.PageChooserBlock())])))])), ('section_break', home.models.SectionBreak()), ('blog_summary', wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock()), ('num_articles', wagtail.core.blocks.IntegerBlock(default=2))])), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'ul', 'link', 'document-link', 'embed', 'h3', 'h4']))], blank=True),
        ),
    ]
